language: python
python:
  - '2.6'
  - '2.7'
matrix:
  allow_failures:
    - python: '2.6'
before_install:
 - pip install scipy
 - pip install pykdtree
 - pip install https://github.com/pytroll/posttroll/archive/develop.tar.gz
 - pip install https://github.com/pytroll/mpop/archive/pre-master.tar.gz
install:
  - pip install .
  - pip install mock
  - pip install coveralls
script: coverage run --source=pytroll_collectors setup.py test
after_success: coveralls
