language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install codecov pytest pytest-cov posttroll pyresample trollsift
  - pip install -e .

script:
  - pytest --cov=./

after_success:
  - codecov
